### ISSUE TITLE
Can't get Faker.dll to work

### ISSUE THREAD

**Issue by GaryGealy** [FermJacob/Faker.Data#1]
I am trying to get this to work with little success. What am I missing?

I have a .Net 4.5 app
 I added the Faker package  to Project via NuGet, 
Add Faker.dll reference to my Project.

Trying:
    Faker.Address f = new Faker.Address();
    var streetName = f.GetCityName();

Gives error:
Faker' does not exist in the current context

Now what?  Is there any documentation?  But this same code compiles without error in the example app

**Comment by FermJacob** [comment]
Hi Gary,

Try something like:
string newName = Faker.Name.FirstName();
or
string lastName = Faker.Name.LastName();

Edit: These are static class's and methods.   You do not need to create a Faker object.

Thanks,
Jake

**Comment by GaryGealy** [comment]
still same error with the code you suggested.  I am still looking and will post back answer when I get one.  Thanks for quick reply

**Comment by FermJacob** [comment]
Let me know.

Are you using .Net 4.5 or 4.5.2?

**Comment by americanslon** [comment]
How was this solved, getting the same error. Both 4.5 and 4.5.2

**Comment by FermJacob** [comment]
What NuGet package are you referencing? Faker.Data?   Gary was referencing the wrong package

**Comment by americanslon** [comment]
Faker.Data
Was getting a warning because I had 4.5 as target. Changed to 4,5,2 warning went away by package still can't be found. What's the "using" library I am supposed to be including, perhaps its VS being silly.

**Comment by FermJacob** [comment]
Just tested to make sure.  Created a console application and referenced the Faker.Data library.  No using class needed since they are static.


namespace FakerTest
{
    class Program
    {
        static void Main(string[] args)
        {
            string address = Faker.Address.USCity();
            string firstName = Faker.Name.FirstName();
            string companyName = Faker.Company.CatchPhrase();
            string lorem = Faker.Lorem.Sentence();
        }
    }
}

**Comment by americanslon** [comment]
Weird, not working for me..

Added Faker.Data through nuget, I can see reference to it in my project references.

using Faker.Data;


 public bool BuildSampleDB(int records, int disposeAfter = 400, bool clear = false)
        {
....
item.Subject = Faker.Lorem.Sentence();

          }

Cant find namespace Faker

**Comment by FermJacob** [comment]
Can you paste your packages.config for me

**Comment by americanslon** [comment]
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Antlr" version="3.4.1.9004" targetFramework="net45" />
  <package id="AutoMapper" version="4.0.0" targetFramework="net45" />
  <package id="bootstrap" version="3.0.0" targetFramework="net45" />
  <package id="EntityFramework" version="6.1.3" targetFramework="net45" />
  <package id="Faker.Data" version="1.0.7" targetFramework="net45" />
  <package id="jQuery" version="1.10.2" targetFramework="net45" />
  <package id="log4net" version="2.0.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.Cors" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.Mvc" version="5.2.2" targetFramework="net45" />
  <package id="Microsoft.AspNet.Razor" version="3.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.SignalR" version="2.2.1" targetFramework="net45" />
  <package id="Microsoft.AspNet.SignalR.Core" version="2.2.1" targetFramework="net45" />
  <package id="Microsoft.AspNet.SignalR.JS" version="2.2.1" targetFramework="net45" />
  <package id="Microsoft.AspNet.SignalR.SystemWeb" version="2.2.1" targetFramework="net45" />
  <package id="Microsoft.AspNet.Web.Optimization" version="1.1.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebApi" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebApi.Client" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebApi.Core" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebApi.Cors" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebApi.HelpPage" version="5.2.2" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebApi.WebHost" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebPages" version="3.2.2" targetFramework="net45" />
  <package id="Microsoft.Owin" version="3.0.1" targetFramework="net45" />
  <package id="Microsoft.Owin.Cors" version="3.0.1" targetFramework="net45" />
  <package id="Microsoft.Owin.Host.SystemWeb" version="2.1.0" targetFramework="net45" />
  <package id="Microsoft.Owin.Security" version="2.1.0" targetFramework="net45" />
  <package id="Microsoft.Web.Infrastructure" version="1.0.0.0" targetFramework="net45" />
  <package id="Modernizr" version="2.6.2" targetFramework="net45" />
  <package id="Newtonsoft.Json" version="6.0.4" targetFramework="net45" />
  <package id="Owin" version="1.0" targetFramework="net45" />
  <package id="RazorEngine" version="3.9.3" targetFramework="net45" />
  <package id="Respond" version="1.2.0" targetFramework="net45" />
  <package id="WebGrease" version="1.5.2" targetFramework="net45" />
</packages>

**Comment by americanslon** [comment]
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Antlr" version="3.4.1.9004" targetFramework="net45" />
  <package id="AutoMapper" version="4.0.0" targetFramework="net45" />
  <package id="bootstrap" version="3.0.0" targetFramework="net45" />
  <package id="EntityFramework" version="6.1.3" targetFramework="net45" />
  <package id="Faker.Data" version="1.0.7" targetFramework="net45" />
  <package id="jQuery" version="1.10.2" targetFramework="net45" />
  <package id="log4net" version="2.0.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.Cors" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.Mvc" version="5.2.2" targetFramework="net45" />
  <package id="Microsoft.AspNet.Razor" version="3.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.SignalR" version="2.2.1" targetFramework="net45" />
  <package id="Microsoft.AspNet.SignalR.Core" version="2.2.1" targetFramework="net45" />
  <package id="Microsoft.AspNet.SignalR.JS" version="2.2.1" targetFramework="net45" />
  <package id="Microsoft.AspNet.SignalR.SystemWeb" version="2.2.1" targetFramework="net45" />
  <package id="Microsoft.AspNet.Web.Optimization" version="1.1.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebApi" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebApi.Client" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebApi.Core" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebApi.Cors" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebApi.HelpPage" version="5.2.2" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebApi.WebHost" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebPages" version="3.2.2" targetFramework="net45" />
  <package id="Microsoft.Owin" version="3.0.1" targetFramework="net45" />
  <package id="Microsoft.Owin.Cors" version="3.0.1" targetFramework="net45" />
  <package id="Microsoft.Owin.Host.SystemWeb" version="2.1.0" targetFramework="net45" />
  <package id="Microsoft.Owin.Security" version="2.1.0" targetFramework="net45" />
  <package id="Microsoft.Web.Infrastructure" version="1.0.0.0" targetFramework="net45" />
  <package id="Modernizr" version="2.6.2" targetFramework="net45" />
  <package id="Newtonsoft.Json" version="6.0.4" targetFramework="net45" />
  <package id="Owin" version="1.0" targetFramework="net45" />
  <package id="RazorEngine" version="3.9.3" targetFramework="net45" />
  <package id="Respond" version="1.2.0" targetFramework="net45" />
  <package id="WebGrease" version="1.5.2" targetFramework="net45" />
</packages>

**Comment by americanslon** [comment]
`<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Antlr" version="3.4.1.9004" targetFramework="net45" />
  <package id="AutoMapper" version="4.0.0" targetFramework="net45" />
  <package id="bootstrap" version="3.0.0" targetFramework="net45" />
  <package id="EntityFramework" version="6.1.3" targetFramework="net45" />
  <package id="Faker.Data" version="1.0.7" targetFramework="net45" />
  <package id="jQuery" version="1.10.2" targetFramework="net45" />
  <package id="log4net" version="2.0.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.Cors" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.Mvc" version="5.2.2" targetFramework="net45" />
  <package id="Microsoft.AspNet.Razor" version="3.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.SignalR" version="2.2.1" targetFramework="net45" />
  <package id="Microsoft.AspNet.SignalR.Core" version="2.2.1" targetFramework="net45" />
  <package id="Microsoft.AspNet.SignalR.JS" version="2.2.1" targetFramework="net45" />
  <package id="Microsoft.AspNet.SignalR.SystemWeb" version="2.2.1" targetFramework="net45" />
  <package id="Microsoft.AspNet.Web.Optimization" version="1.1.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebApi" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebApi.Client" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebApi.Core" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebApi.Cors" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebApi.HelpPage" version="5.2.2" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebApi.WebHost" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebPages" version="3.2.2" targetFramework="net45" />
  <package id="Microsoft.Owin" version="3.0.1" targetFramework="net45" />
  <package id="Microsoft.Owin.Cors" version="3.0.1" targetFramework="net45" />
  <package id="Microsoft.Owin.Host.SystemWeb" version="2.1.0" targetFramework="net45" />
  <package id="Microsoft.Owin.Security" version="2.1.0" targetFramework="net45" />
  <package id="Microsoft.Web.Infrastructure" version="1.0.0.0" targetFramework="net45" />
  <package id="Modernizr" version="2.6.2" targetFramework="net45" />
  <package id="Newtonsoft.Json" version="6.0.4" targetFramework="net45" />
  <package id="Owin" version="1.0" targetFramework="net45" />
  <package id="RazorEngine" version="3.9.3" targetFramework="net45" />
  <package id="Respond" version="1.2.0" targetFramework="net45" />
  <package id="WebGrease" version="1.5.2" targetFramework="net45" />
</packages>`

**Comment by FermJacob** [comment]
Can you create a sample console application and see if you can replicate the issue?  If you can, send me the source files of that console app to my email in my profile and I can try to reproduce the issue.

**Comment by americanslon** [comment]
Ooo lawd....I have a solution with quite a few projects and I have been adding  and re-adding Faker into the wrong one. I can't even. Sorry for wasting your time.
