### ISSUE TITLE
public DateTime GetDateBetween(DateTime from, DateTime to)   - always returning same value

### ISSUE THREAD

**Issue by GaryGealy** [FermJacob/Faker.Data#2]
This returns the 'From" value every time. In this case 12/1/2015

Faker.Date fd = new Faker.Date();
newTicket.TimeStamp = fd.GetDateBetween( new DateTime(2015, 12, 01), DateTime.Now);

**Comment by FermJacob** [comment]
Hi Gary,

Are you using Faker.Data or Faker.Net? 

Faker.Data (this project) does not have any code for GetDateBetween

Please look at this url https://github.com/Kuree/Faker.Net which has your example method.

**Comment by GaryGealy** [comment]
Sorry, I was mistaken.  Faker.Net is what I was looking at.  Still a little
confused on what does what there are something 44 C# projects for Faker on
Github.  But that's opensource for ya.

Thanks for the help.

-GmG-

On Tue, Mar 1, 2016 at 3:59 PM, Jacob Ferm notifications@github.com wrote:

> Hi Gary,
> 
> Are you using Faker.Data or Faker.Net?
> 
> Faker.Data (this project) does not have any code for GetDateBetween
> 
> Please look at this url https://github.com/Kuree/Faker.Net which has your
> example method.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/FermJacob/Faker.Data/issues/2#issuecomment-190924528.

## 

-GmG-
