### ISSUE TITLE
Gender doesn't seem very 50/50

### ISSUE THREAD

**Issue by jonathh21** [FermJacob/Faker.Data#3]
I suspect it relates to the random between 0 1 equals 0.
I don't know off the top of my head what 0.4 == 0 will result in.... But I have generated hundreds of datasets and not send any women!

Thanks

**Comment by FermJacob** [comment]
Hey, I have confirmed the issue on my end as well.  I am changing the logic a little to get more probability

**Comment by FermJacob** [comment]
Pushed 1.0.8 to nuget
